vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: ~
            upload_destination: '%kernel.project_dir%/public/uploads/articles'
            namer: App\Service\S3StorageNamer
            directory_namer: ~